### PR TITLE
Initial Python version

### PR DESCRIPTION
**Pull request by zmoon**
Implemented:
* Automatic loading and caching of CRN daily data, ALEXI daily ET, and PRISM daily P data from their remote sources
  - note that ALEXI ET seems to be no longer available during current year (2023)
* Multiple initial condition options, including based on CRN SM
* Integration (applying P - ET using the stored slope weights to compute next day's SM)
* Python packaging
* Example plots
* Development setup instructions
* pre-commit checks

Not (yet?) implemented:
* (re)creating the weights
* using min/maxmoist to clip
* (re)creating min/maxmoist for different time periods
* using local ALEXI ET nc archive
  - need this to some extent since less available
* `smn` (the non-weighted version in the original code)
   - should do this, since the original code seems to consider `sm - smn` (the diff) a product as well
   - included in #2 
* mm units option (instead of current m3 m-3)

### CODE REVIEW

**Comment by zmoon** [comment]
Planning to merge this soon, so can address remaining with targeted issues and PRs.

**Comment by bbakernoaa** [comment]
@zmoon Thanks for all of your hard work

**Comment by zmoon** [comment]
@drnimbusrain reminded that the Python package name should be `swampy` or `swamppy`...

**Comment by drnimbusrain** [comment]
Definitely needed, and you get the credit for that!

**Comment by zmoon** [comment]
@drnimbusrain can you merge this or give me access to do so?

**Comment by drnimbusrain** [comment]
@zmoon I have updated your permissions so you are now admin of this repository.  Go ahead and merge.

**Pull request merged**
